### ISSUE TITLE
Required fields Issue

### ISSUE THREAD

**Issue by ank1traj** [NikhilJoshua/thelazyentry#4]
### Environment
**OS - Windows
Browser - Chrome
Architecture - x64
Site URL -** https://nikhiljoshua.github.io/thelazyentry/

| name  | About  | labels  | assignees|
|---|---|---|---|
|  🐛 UX Issue Report |  Required Field is not visible🤔. | UX Issue|   |

**Description** - On clicking **Add** when no data is inserted, it shows an error that **Please Fill all the required fields**
** but which one is required field is not clear.

**Expected** - There should be a clear way to recognize the required field.

**Actual** - Required field can't be distinguished.

![image](https://user-images.githubusercontent.com/32160084/133045555-51c033aa-e592-4c3a-8b1e-d137757bfd43.png)

**Comment by NikhilJoshua** [comment]
Thanks @ank1traj Will be working on it async.

**Comment by NikhilJoshua** [comment]
@ank1traj The issue has been resolved. Please check and close the issue if everything works fine.

**Comment by NikhilJoshua** [comment]
## Added 
- Required fields will get red * when the value is not entered.
![image](https://user-images.githubusercontent.com/8474784/133091025-70566c94-c6b1-413b-88b1-d61e7f43bf0c.png)

**Comment by ank1traj** [comment]
The issue has been fixed. So, closing this issue.

Thanks, @NikhilJoshua @sroshan106 for the quick response.
